import type { Metadata } from "next";
import "./globals.css";
import "modern-normalize";
import { Manrope } from "next/font/google";
import { Header } from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "RentalCars",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  variable: "--font-manrope",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
